name: BDJSkyBlock
author: BlazeDotJar
version: 0.10.1_3
api-version: 1.21
depend:
  - 'BDJPlaceholder'
  - 'WorldEdit'
main: de.bdj.sb.SB
commands:
  sb:
    description: 'SkyBlock main command for admins+'
  sbdev:
    description: 'BlazeDotJar analysis command'
  is:
    description: 'Island main command for players'
permissions:
  #--Dev permissions-----------------------------------------------------
  bdj.sb.*:
    description: 'Give this permission only to developers'
    children:
      bdj.sb.admin: true
  #--Admin permissions-----------------------------------------------------
  bdj.sb.admin:
    description: 'Give this permission to all admins.'
    children:
      bdj.sb: true
      bdj.sb.rl: true
      bdj.sb.swl: true
      bdj.sb.twl: true
      bdj.sb.claimed: true
      bdj.sb.islands: true
      bdj.sb.tp: true
      bdj.sb.release: true
      bdj.sb.adminhelp: true
  bdj.sb:
    description: 'Help command'
  bdj.sb.rl:
    description: 'Reload settings'
  bdj.sb.swl:
    description: 'Set waitlobby location'
  bdj.sb.twl:
    description: 'teleport to waitlobby location'
  bdj.sb.claimed:
    description: 'List all claimed islands in a given range'
  bdj.sb.islands:
    description: 'List all islands in a given range'
  bdj.sb.tp:
    description: 'Teleort to an island'
  bdj.sb.release:
    description: 'Release an island to the market'
  bdj.sb.adminhelp:
    description: 'Show help for admins'
  #--Gameplay permissions-----------------------------------------------------
  bdj.is.*:
    description: 'Give this permission to all players'
    children:
      bdj.is: true
      bdj.is.create: true
      bdj.is.help: true
      bdj.is.delete: true
      bdj.is.member: true
      bdj.is.quit: true
      bdj.is.ban: true
      bdj.is.confirm: true
  bdj.is:
    description: 'Teleport to your island'
  bdj.is.create:
    description: 'Create an island'
  bdj.is.help:
    description: 'Show command help'
  bdj.is.delete:
    description: 'Delete your island'
  bdj.is.member:
    description: 'Accept Member Invitation'
  bdj.is.quit:
    description: 'Quit an membered island'
  bdj.is.ban:
    description: 'Ban a player from your island'
  bdj.is.confirm:
    description: 'Confirm a critical task'