name: BDJSkyBlock
author: BlazeDotJar
version: 0.0.1_0
api-version: 1.21
main: de.bdj.sb.SB
commands:
  sb:
    description: 'Help command'
  sbdev:
    description: 'BlazeDotJar analysis command'
permissions:
  bdj.sb.*:
    description: 'Give this permission only to developers'
    children:
      bdj.sb.admin: true
  bdj .sb.admin:
    description: 'Give this permission to all admins.'
    children:
      bdj.sb: true
      bdj.sb.rl: true
      bdj.sb.swl: true
  bdj.sb:
    description: 'Help command'
  bdj.sb.rl:
    description: 'Reload settings'
  bdj.sb.swl:
    description: 'Set waitlobby location'