package de.bdj.sb.gui.management;

public enum GuiButtonType {

    CREATE_CLASSIC_SKYBLOCK,
    CREATE_ONE_BLOCK_SKYBLOCK,
    ISLAND_TELEPORT,
    ISLAND_QUESTS,
    ISLAND_PROPERTIES,
    BACK_TO_DASHBOARD,
    PROP_BTN_ALLON,
    PROP_BTN_ALLOFF,
    PROP_STATE_ON,
    PROP_STATE_OFF,
    PROP_PVP,
    PROP_MOB_GRIEFING,
    PROP_EXPLOSION_DAMAGE,
    PROP_TNT_DAMAGE,
    PROP_SPREAD_FIRE,
    PROP_NATURAL_MONSTER_SPAWN,
    PROP_MOB_KILLING,
    KILL_MONSTERS,
    SET_ISLAND_SPAWN,
    RELOAD_DATA,
    MEMBERS_GUI,
    DEV_TOOL_BIOME_CHANGE,
    DEV_BUILD_COL,
    DEV_BUILD_COL_2,
    BACK_TO_QUESTS,
    QUEST_FARM_COBBLE_BTN,
    QUEST_FARM_LOG_BTN,
    QUEST_BUILD_COBBLE_GENERATOR_BTN;

}
